---
  handlers:
    - name: restart nginx
      become: true
      service:
        name: nginx
        state: restarted
    - name: restart ntp
      become: true
      service:
        name: ntp
        state: restarted