---
- hosts: rumba
  remote_user: seg
  tasks:
    - name: Test connection
      ping:
    - name: Install byobu
      become: true
      apt:
        package: byobu
        state: installed
        update_cache: true
    - name: Deploy software
      command: sh ~/code/rumba/backend/utils/scripts/deploy_on_byobu.sh
