---
- hosts: rumba
  remote_user: seg
  vars_files:
    - ../etc/variables.yml
  tasks:
    - name: test connection
      ping:
    - name: NGINX installation
      apt: pkg=nginx state=installed update_cache=true
      become: true
    - name: Configure NGINX proxy
      template: src=etc/nginx.conf.tpl dest=/etc/nginx/nginx.conf
      become: true
    - name: Configure NGINX for Janus
      template:
        src: etc/nginx-default-site
        dest: /etc/nginx/sites-available/default
      notify:
        -restart nginx
  handlers:
    - name: restart nginx
      become: true
      service: name=nginx state=restarted