---
- hosts: rumba
  remote_user: seg
  vars_files:
    - etc/variables.yml
  tasks:
    - name: test connection
      ping:
    - name: NGINX installation
      apt: pkg=nginx state=installed update_cache=true
      become: true
    - name: NGINX setup
      template: src=etc/nginx.conf.tpl dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: true
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted