---
- hosts: rumba
  remote_user: seg
  vars_files:
    - ../etc/variables.yml
  tasks:
    - name: test connecton
      ping:
    - name: NTP server installation
      become: true
      apt:
        pkg: ntp
      state: present
        update_cache: true
    - name: Configure NTP server
      become: true
      copy:
        src: ../etc/ntp.conf
        dest: /etc/ntp.conf
      notify:
        - restart ntp
  handlers:
    - name: restart ntp
      become: true
      service:
        name: ntp
        state: restarted
