---
- hosts: rumba
  remote_user: seg
  vars_files:
    - ../etc/variables.yml
  tasks:
    - name: test connection
      ping:
    - name: Install dependencies
      become: true
      apt:
        package: "{{ item }}"
        state: installed
        update_cache: true
      with_items:
        - build-essential
        - python-dev
    - name: Install pip
      become: true
      apt:
        package: python-pip
        state: installed
        update_cache: true

      ###########################
      ###  Mongo installation ###
      ###########################

    - name: Install pymongo
      pip:
        name: pymongo
      become: true
    - name: Prepare mongodb installation
      become: true
      command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    - name: Add mongodb sources
      shell: echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.6.list
      become: true
    - name: Install mongodb
      become: true
      apt:
        package: mongodb-org
        state: installed
        update_cache: true

      ##########################
      ## Backend installation ##
      ##########################
      
    - name: Install virtualenv
      become: true
      pip:
        name: virtualenv
    - name: Create virtual environment
      command: virtualenv ~/code/rumba/backend/venv -p python3.4
    - name: Install python dependencies
      pip:
        name: egg
        chdir: "~/code/rumba/backend"
        extra_args: "-e ."
        virtualenv: "~/code/rumba/backend/venv"
    - name: Create logs directory
      file:
        path: "~/code/rumba/backend/logs"
        state: directory
