---

  - include: janus-dependencies.yml
  - include: boring-ssl.yml
  - include: libsrtp.yml
  - include: livewebsockets.yml
  - include: usrsctp.yml

  - name: Create directory for Janus code
    file:
      path: ~/code/janus
      state: directory
  - name: Download Janus code
    git:
      repo: https://github.com/meetecho/janus-gateway.git
      dest: ~/code/janus
      version: v0.3.0
  - name: Create directory for Janus
    become: true
    file:
      path: "{{ janus_dir }}"
      state: directory
      owner: seg # TODO use defined user
      group: seg
  - name: Generate configuration file
    shell: sh autogen.sh
    args:
      chdir: ~/code/janus/
  - name: Build janus-gateway (no RabbitMQ, no MQTT, use BoringSSL)
    command: "./configure --prefix={{ janus_dir }} --disable-rabbitmq --disable-mqtt --enable-boringssl"
    args:
      chdir: ~/code/janus/
  - name: Install Janus
    command: "{{ item }}"
    args:
      chdir: ~/code/janus/
    with_items:
      - make install
      - make configs
  - name: Enable HTTPs in Janus
    copy:
      src: ../../etc/janus.transport.http.cfg
      dest: "{{ janus_dir }}/etc/janus/janus.transport.http.cfg"
