---

  - include_tasks: janus-dependencies.yml
  - include_tasks: boring-ssl.yml
  - include_tasks: libsrtp.yml
  - include_tasks: livewebsockets.yml
  - include_tasks: usrsctp.yml

  - name: Copy the code to the server
    copy:
      src: "{{ playbook_dir }}/../janus"
      dest: /tmp/
  - name: Create directory for Janus
    become: true
    file:
      path: "{{ janus_dir }}"
      state: directory
      owner: "{{ ubuntu_user }}"
      group: "{{ ubuntu_user }}"
  - name: Generate configuration file
    shell: sh autogen.sh
    args:
      chdir: /tmp/janus/
  - name: Build janus-gateway (no RabbitMQ, no MQTT, use BoringSSL)
    command: "./configure --prefix={{ janus_dir }} --disable-rabbitmq --disable-mqtt --enable-boringssl"
    args:
      chdir: /tmp/janus/
  - name: Install Janus
    command: "{{ item }}"
    args:
      chdir: /tmp/janus/
    with_items:
      - make install
      - make configs
  - name: Enable HTTPs in Janus
    copy:
      src: ../../files/janus.transport.http.cfg
      dest: "{{ janus_dir }}/etc/janus/janus.transport.http.cfg"
  - name: Copy ServerDate library
    copy:
      src: ../../files/ServerDate.js
      dest:  "{{ janus_dir }}/share/janus/demos/ServerDate.js"
