---

  - include_tasks: janus-dependencies.yml
  - include_tasks: boring-ssl.yml
  - include_tasks: libsrtp.yml
  - include_tasks: livewebsockets.yml
  - include_tasks: usrsctp.yml

  - name: Create directory for Janus code
    file:
      path: /tmp/janus
      state: directory
  - name: Download Janus code
    git:
      repo: https://github.com/meetecho/janus-gateway
      dest: /tmp/janus
      version: v0.3.0
  - name: Create directory for Janus
    become: true
    file:
      path: "{{ janus_dir }}"
      state: directory
      owner: seg # TODO use defined user
      group: seg
  - name: Generate configuration file
    shell: sh autogen.sh
    args:
      chdir: /tmp/janus/
  - name: Build janus-gateway (no RabbitMQ, no MQTT, use BoringSSL)
    command: "./configure --prefix={{ janus_dir }} --disable-rabbitmq --disable-mqtt --enable-boringssl"
    args:
      chdir: /tmp/janus/
  - name: Install Janus
    command: "{{ item }}"
    args:
      chdir: /tmp/janus/
    with_items:
      - make install
      - make configs
  - name: Enable HTTPs in Janus
    copy:
      src: ../../files/janus.transport.http.cfg
      dest: "{{ janus_dir }}/etc/janus/janus.transport.http.cfg"
